trigger:
  - main

variables:
  tag: "$(Build.BuildId)"
  image: faaideen/website

resources:
  repositories:
    - repository: templates
      type: github
      name: SierraSoftworks/devops-pipelines
      endpoint: SierraSoftworks

extends:
  template: kubernetes/app.yml@templates
  parameters:
    build:
      - job: build_docker
        displayName: Build Docker Image
        steps:
          - task: Docker@2
            displayName: Build Docker Image
            inputs:
              command: buildAndPush
              dockerfile: "Dockerfile"
              containerRegistry: Docker Hub
              repository: $(image)
              tags: |
                latest
                $(tag)
    manifests: ./.deploy
    containers: |
      $(image):$(tag)
    staging:
      namespace: aideen-website-staging
      environment: staging-api-aideen-dev
      healthcheck: https://api.aideen.dev/books
    production:
      namespace: aideen-website-prod
      environment: api-aideen-dev
      healthcheck: https://api.aideen.dev/books
