---
apiVersion: v1
kind: Service
metadata:
  name: aideen-website-server
spec:
  selector:
    app.kubernetes.io/name: aideen-website
    app.kubernetes.io/instance: aideen-website-server
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 80 # abstracted Service port which can be any port other pods used to access the service
      targetPort: 8000 # the port the container accepts traffic on
