name: Deploy Website
on: 
  push:
    branches: [main]

env:
  LIVE_FUNCTION_NAME: blog-aideen
  LIVE_HEALTH_CHECK:  https://api.aideen.dev/books|https://www.aideen.dev/library

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Checkout Github Action
        uses: actions/checkout@v2

      - name: Build Handler
        run: go build -o handler main.go

      - name: Save handler artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-handler
          path: handler

  deploy:

    needs: [build]
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v2

      - name: Fetch handler artifact
        uses: actions/download-artifact@v2
        with:
          name: built-handler

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.LIVE_FUNCTION_NAME }}
          respect-funcignore: 'true'

  healthcheck:

    needs: [deploy]
    
    runs-on: ubuntu-latest

    steps:
      - name: Probe
        uses: Jtalk/url-health-check-action@v1.3
        with:
          url: ${{ env.LIVE_HEALTHCHECK }}
          max-attempts: 4
          retry-delay: 5s





    

  

